apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: sindan-server
    region: ap-northeast-1

vpc:
  subnets:
    private:
      ap-northeast-1a: { id: subnet-004a4c445b1731440 }
      ap-northeast-1c: { id: subnet-04e857fb2f1902d30 }
      ap-northeast-1d: { id: subnet-034d814868f33b963 }

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      publicKeyPath: ~/.ssh/MASTER/mi2428.master.id_rsa.pub
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
    ssh:
      publicKeyPath: ~/.ssh/MASTER/mi2428.master.id_rsa.pub
