apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.1.52
    path: /mnt/array1/dump
