apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-read-performance-test
spec:
  template:
    metadata:
      name: nfs-read-performance-test
    spec:
      containers:
        - image: ubuntu:18.04
          name: nfs-read-performance-test
          command: ["dd", "if=/mnt/pv/test.img", "of=/dev/null", "bs=8k"]
          volumeMounts:
            - mountPath: /mnt/pv
              name: target-nfs
      volumes:
        - name: target-nfs
          persistentVolumeClaim:
            claimName: nfs-pv-claim-test
      restartPolicy: Never
