apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim-test
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
