apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound-deployment
  labels:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-31T23:23:03Z"
  generation: 1

<<: &healthcheck-template
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 2

spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: unbound
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unbound
    spec:
      containers:
        - name: healthz
          image: googlecontainer/exechealthz:1.2
          imagePullPolicy: IfNotPresent
          args:
            - "-cmd=nslookup health.check.unbound. 127.0.0.1:53 > /dev/null"
          ports:
            - name: healthz
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "1m"
        - name: unbound
          image: 203.178.158.5:30500/wide-camp-1909/camp-dns-unbound:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          resources:
            requests:
              cpu: "1000m"
          readinessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 1
          livenessProbe:
            <<: *healthcheck-template
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: unbound-conf
              mountPath: "/opt/unbound/etc/unbound/"
              readOnly: true
            - name: rsyslogd-conf
              mountPath: "/opt/rsyslogd/etc/"
              readOnly: true
      volumes:
        - name: unbound-conf
          configMap:
            name: unbound-configmap
        - name: rsyslogd-conf
          configMap:
            name: rsyslogd-configmap

