apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: unbound-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unbound-deployment
  minReplicas: 2
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
